development:
  adapter: mysql2
  database: la_dev
  host: 127.0.0.1
  username: root
  password: 
  pool: 20

test:
  adapter: mysql2
  database: la_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: la_prod
  host: 127.0.0.1
  username: root 
  password: 
  pool: 20